run: exit status 1
[0m[1m[31merror[0m: Uncaught (in promise) Error: capture_area failed
function _panic(msg: any): never { throw new Error(String(msg)); }
[0m[31m                                         ^[0m
    at [0m[1m[3m_panic[0m ([0m[36mfile:///workspace/mochi/tests/algorithms/x/TypeScript/physics/basic_orbital_capture.ts[0m:[0m[33m129[0m:[0m[33m42[0m)
    at [0m[1m[3mrun_tests[0m ([0m[36mfile:///workspace/mochi/tests/algorithms/x/TypeScript/physics/basic_orbital_capture.ts[0m:[0m[33m62[0m:[0m[33m5[0m)
    at [0m[1m[3mmain[0m ([0m[36mfile:///workspace/mochi/tests/algorithms/x/TypeScript/physics/basic_orbital_capture.ts[0m:[0m[33m66[0m:[0m[33m3[0m)
    at [0m[36mfile:///workspace/mochi/tests/algorithms/x/TypeScript/physics/basic_orbital_capture.ts[0m:[0m[33m134[0m:[0m[33m3[0m
    at [0m[36mfile:///workspace/mochi/tests/algorithms/x/TypeScript/physics/basic_orbital_capture.ts[0m:[0m[33m146[0m:[0m[33m2[0m
